-- Database: GLOBALPLA Metadata version: 2 Exported: Oct 7, 2021
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6482_Label_BI" USING 'GCG_6482_Label_BI.mkd' PAGESIZE=4096 (
 "TERMINAL" INTEGER,
 "USER_ID" CHAR(8),
 "SEQUENCE" CHAR(4),
 "PART" CHAR(20),
 "DESCRIPTION" CHAR(128),
 "DATE_MANUF" DATETIME,
 "TYPE" CHAR(16),
 "LINE" CHAR(16),
 "SIZE" CHAR(24),
 "COLOR" CHAR(32),
 "HARDWARE" CHAR(128),
 "MOUNTING" CHAR(128),
 "NEMA" CHAR(12),
 "CE" CHAR(1),
 "UL" CHAR(20),
 "BARCODE" CHAR(20),
 "QUANTITY" DOUBLE,
 "USERDATA1" CHAR(50),
 "PART_INTERNAL" CHAR(20),
 "DESC_INTERNAL" CHAR(128),
 "SERIAL_NUM" INTEGER,
 "CUSTOMER" CHAR(6),
 "NAME_CUSTOMER" CHAR(30),
 "SALES_ORDER" CHAR(7),
 "DATE_PRINT" DATE );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
