-- Database: GLOBALPLA Metadata version: 2 Exported: Oct 7, 2021
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6482_Label_Metadata" USING 'GCG_6482_Label_Metadata.mkd' PAGESIZE=4096 (
 "PARTNUMBER" CHAR(128),
 "TYPE" CHAR(16),
 "LINE" CHAR(16),
 "SIZE" CHAR(24),
 "COLOR" CHAR(32),
 "HARDWARE" CHAR(128),
 "MOUNTING" CHAR(128),
 "NEMA" CHAR(12),
 "CE" INTEGER,
 "UL" CHAR(20),
 "BARCODE" CHAR(20),
 "DESCRIPTIONOVERRIDE" CHAR(256),
 "REPORTOVERRIDE" CHAR(45),
 "REPORTOVERRIDE2" CHAR(45),
 "USERDATA1" CHAR(256),
 "ADDITIONALREPORT" BIT NOT NULL,
 "COMPANYCODE" CHAR(3),
 "USEMULTI" INTEGER );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
