-- Database: GLOBALPLA Metadata version: 2 Exported: Oct 28, 2021
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6482_Label_Log" USING 'GCG_6482_Label_Log.mkd' PAGESIZE=4096 (
 "LOG_ID" BIGIDENTITY DEFAULT '0' CONSTRAINT "UK_LOG_ID" UNIQUE USING 0,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "ORDER_NO" CHAR(7),
 "PART" CHAR(20),
 "QTY_JOB" DOUBLE,
 "QTY_PRINT" DOUBLE,
 "DATE_PRINT" DATETIME,
 "USER_PRINT" CHAR(8),
 "AUTHORIZATION" CHAR(30) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
