-- Database: GLOBALPLA Metadata version: 2 Exported: Nov 9, 2021
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6482_LABEL_CUSTOMER" USING 'GCG_6482_LABEL_CUSTOMER.mkd' PAGESIZE=4096 (
 "LABEL_ID" CHAR(6),
 "CUSTOMER" CHAR(8),
 "NAME" CHAR(128),
 "REPORT" LONGVARCHAR,
 "PRINTERSIZE" CHAR(12),
 "LABEL_TYPE" CHAR(30),
 "BI_ID" CHAR(50) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
