-- Database: GLOBALPLA Metadata version: 2 Exported: Oct 7, 2021
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6482_Label_Serial" USING 'GCG_6482_Label_Serial.mkd' PAGESIZE=4096 (
 "SERIAL_NUMBER" BIGIDENTITY DEFAULT '0' CONSTRAINT "UK_SERIAL_NUMBER" UNIQUE USING 0,
 "MODEL" CHAR(50),
 "DATE_MFG" DATE,
 "CUSTOMER" CHAR(50),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "PART" CHAR(20),
 "QTY_JOB" DOUBLE,
 "QTY_PRINT" DOUBLE,
 "DATE_PRINT" DATE,
 "NOTES" LONGVARCHAR,
 "EMPLOYEEID" CHAR(50),
 "SCRAPPED" DOUBLE,
 "AUTHORIZATION" CHAR(30) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
